### PR TITLE
Setting up a Django development environment

### LINKED ISSUE #6: Setting up a Django development environment
after @Yuval-Vino will create a Linux development environment with Vagrantfile, I will create:
- [ ]  Software dependency management by updating the Pipenv that will work on Python 3.
- [ ] Installing Django framework to our project.
- [ ]  Bootstrapping a Django website.
- [ ]  Providing HTTP access into our VM (by using port forwarding).

### PR DESCRIPTION
**Pull request by ErezCohenn**
- [x]  Software dependency management by updating the Pipenv that will work on Python 3.
- [x] Installing Django framework to our project.
- [x]  Bootstrapping a Django website.
- [x]  Providing HTTP access into our VM (by using port forwarding).

Closes #6

### CODE REVIEW

**Comment by tamirmatok** [comment]
Hi. Files looks good ,but im not sure why we have duplicates files in diffrent directories, for example : manage.py and asgi appears twice .I think only init, asgi, settings, urls and wsgi should be in Hotails directory and the others (pipfile, pipfile.lock and manage) should appear outside Hotails directory .

**Review by tamirmatok — COMMENTED** [review]
LGTM

**Comment by ErezCohenn** [comment]
You're right, I don't know why it duplicated all the files, but now it's fixed.

**Comment by OfirMatasas** [comment]
Looks good to me.
Great job @ErezCohenn !

**Review by jeniaSakirko — APPROVED** [review]
LGTM

**Review by tamirmatok — APPROVED** [review]

**Review by Yuval-Vino — APPROVED** [review]

**Review by Omeramsc — APPROVED** [review]
LGTM

**Review by ormergi — CHANGES_REQUESTED** [review]
Hi Erez, 
Please make sure you add sing-off-by for each commit.
Regarding the commit message style, try to avoid using first person pronounce (e.g: I, we, our..) when possible, its better to keep the commit message style in an imperative way, 
for example something like :
      _manage.py: is being used to test and run Hottails app.
      Also, all bootstrap files are moved to Hotails directory._

**Comment by ErezCohenn** [comment]
> Hi Erez, Please make sure you add sing-off-by for each commit. Regarding the commit message style, try to avoid using first person pronounce (e.g: I, we, our..) when possible, its better to keep the commit message style in an imperative way, for example something like : _manage.py: is being used to test and run Hottails app. Also, all bootstrap files are moved to Hotails directory._

Fixed

**Comment by Omeramsc** [comment]
please fix conflicts
(in order to fix a Pipfile.lock conflict, remove the existing one and re-create it)

**Comment by ErezCohenn** [comment]
> please fix conflicts (in order to fix a Pipfile.lock conflict, remove the existing one and re-create it)

Done

**Pull request merged**
