### PR TITLE
📈 Adding the ERD diagram to the README.md and adding the abillity to edit the ERD

### PR DESCRIPTION
**Pull request by ErezCohenn**
- [x] Adding ERD diagram to README.md
- [x] Adding ERD diagram to resources/documents/README.md
- [x] Adding the option for the contributions to appeal a request to edit the ERD diagram 

Depends #40  (update: #40 merged, ready to approve)
Closing #42

### CODE REVIEW

**Review by OfirMatasas — APPROVED** [review]
LGTM

**Review by jeniaSakirko — APPROVED** [review]
LGTM
This PR should be pushed after #40

**Comment by ErezCohenn** [comment]
> LGTM This PR should be pushed after #40

You're righy, changed the description

**Review by Yuval-Vino — APPROVED** [review]

**Review by ormergi — CHANGES_REQUESTED** [review]
Please squash intermediate commits according to https://github.com/redhat-beyond/Hotails/blob/main/Contributing.md

**Comment by ErezCohenn** [comment]
> Please squash intermediate commits according to https://github.com/redhat-beyond/Hotails/blob/main/Contributing.md

Done @ormergi

**Review by ormergi — APPROVED** [review]
Thanks

**Pull request merged**
