### PR TITLE
Updating ERD

### LINKED ISSUE #81: Update Hotails ERD
## Expected Behavior

ERD will contain only relevant fields of each DB 

## Current Behavior

Message contains Message_reply field that is outdate, VSDX file is messy

## Acceptance Criteria

Update ERD,  arrange VSDX file, remove outdated fields

### PR DESCRIPTION
**Pull request by Yuval-Vino**
### Desired Outcome

arranged and up-to-date ERD

### Implemented Changes

arranged VSDX file to be more readable
removed outdated field - from message DB message_reply

### Connected Issue/Story

Resolves #81 

#### Changelog

- [ ] The CHANGELOG has been updated
- [X] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes
- [X] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [X] This PR does not require updating any documentation

### CODE REVIEW

**Review by ErezCohenn — APPROVED** [review]
LGTM !

**Comment by Omeramsc** [comment]
LGTM

**Comment by Omeramsc** [comment]
LGTM
please have all team members review it and ping me for merge.

**Review by jeniaSakirko — APPROVED** [review]
LGTM

**Review by tamirmatok — APPROVED** [review]
LGTM

**Review by ormergi — APPROVED** [review]
LGTM

**Review by Omeramsc — CHANGES_REQUESTED** [review]
Is a `VSDX` more readable? I can't open it on GH/my machine.

**Comment by Yuval-Vino** [comment]
> Is a `VSDX` more readable? I can't open it on GH/my machine.

we always had a VSDX file, I just updated it, 
 Do you think it's better to switch the type of the file? if so which type ?

**Comment by Omeramsc** [comment]
> > Is a `VSDX` more readable? I can't open it on GH/my machine.
> 
> we always had a VSDX file, I just updated it, Do you think it's better to switch the type of the file? if so which type ?

Sorry, I misunderstood, thought you removed the image in favor of the VSDX. 
LGTM.

**Pull request merged**
