### PR TITLE
📈 Creating ERD diagram

### PR DESCRIPTION
**Pull request by ErezCohenn**
The ERD diagram represents the data model and business logic for the web application.
The database that will be built for each application will be based on that diagram.

Closing #20

### CODE REVIEW

**Review by OfirMatasas — CHANGES_REQUESTED** [review]
Great job overall. Few things to take into consideration:
1. Delete the status options in the Order table, as we don't have this kind of information in any other field over the diagram.
2. Add variable types in all fields, for better synchronization between the models, when working parallelly. For example, in Dog Owner, the dog name can be TextField(20), and Dog age can be Integer.
3. The logo added to the ERD is not the logo of our project. Either change it to the correct one or remove it.

**Comment by ormergi** [comment]
Could you please explain what is the "User" entity is used for?

**Comment by ormergi** [comment]
Hi Erez,
Could you please give some context of who is the `User` entity?
As far as I understand there is already an entity to represent a user which is `DogOwner`,
why is it necessary to have another one?

**Comment by ErezCohenn** [comment]
> Great job overall. Few things to take into consideration:
> 
> 1. Delete the status options in the Order table, as we don't have this kind of information in any other field over the diagram.
> 2. Add variable types in all fields, for better synchronization between the models, when working parallelly. For example, in Dog Owner, the dog name can be TextField(20), and Dog age can be Integer.
> 3. The logo added to the ERD is not the logo of our project. Either change it to the correct one or remove it.

1. I think that the field `Status` is not recognized in any other table is not a reason to delete it. I think that this is a necessary field for order reservation. tell me what u think team and we will decide about it together
2. Agree, I will add that soon.
3. Good cathing, will be changed either.

**Comment by OfirMatasas** [comment]
> > Great job overall. Few things to take into consideration:
> > 
> > 1. Delete the status options in the Order table, as we don't have this kind of information in any other field over the diagram.
> > 2. Add variable types in all fields, for better synchronization between the models, when working parallelly. For example, in Dog Owner, the dog name can be TextField(20), and Dog age can be Integer.
> > 3. The logo added to the ERD is not the logo of our project. Either change it to the correct one or remove it.
> 
> 1. I think that the field `Status` is not recognized in any other table is not a reason to delete it. I think that this is a necessary field for order reservation. tell me what u think team and we will decide about it together
> 2. Agree, I will add that soon.
> 3. Good cathing, will be changed either.

About 1, you got a point. Either keeping it or deleting it works for me.

**Review by OfirMatasas — APPROVED** [review]

**Review by tamirmatok — CHANGES_REQUESTED** [review]
> Hi Erez, Could you please give some context of who is the `User` entity? As far as I understand there is already an entity to represent a user which is `DogOwner`, why is it necessary to have another one?

Agree with that . I think it would be better to delete 'User' entity and modify 'DayCare' and 'DogOwner' as needed .

**Comment by ErezCohenn** [comment]
> modify

I agree, but I think we are still want to use the `User` entity that is build-in Django that will make it easier for us to manage users.
 Someone knows if there is a way we can use the `User` entity and insert fields to him so that at the end we will stay with 2 entities: `DayCare` and `DogOwner` that have common fields that exist in a `User` entity instead of 3 entities.

**Review by jeniaSakirko — COMMENTED** [review]
@ErezCohenn can you add the file so we could work on it together?

**Review by Omeramsc — CHANGES_REQUESTED** [review]
- I think you can keep `User`, but it shouldn't include the first\last name or phone number. if those are relevant, they can be placed in the entity itself.
- separate the line from user to `Dog Owner` and `DayCare`. it is confusing, as those entities are not related to each other.
- nit: s/DayCare/Day Care, or remove the spaces in all enteties.
- What does `PropertyID` under `ReviewBoard` refers to? is should be clear. I also don't think `ReviewBoard` should be an entity at all, it is a feature that is using the `review` entity.
- Same goes for `Message Boards`

**Comment by ErezCohenn** [comment]
> @ErezCohenn can you add the file so we could work on it together?
I added the online editor link to the issue so anyone will be able to edit the diagram.
Take a look here: #20

**Comment by Omeramsc** [comment]
what happens when a Dogowner has more than one dog?

**Comment by ErezCohenn** [comment]
> * I think you can keep `User`, but it shouldn't include the first\last name or phone number. if those are relevant, they can be placed in the entity itself.
> * separate the line from user to `Dog Owner` and `DayCare`. it is confusing, as those entities are not related to each other.
> * nit: s/DayCare/Day Care, or remove the spaces in all entities.
> * What does `PropertyID` under `ReviewBoard` refers to? it should be clear.
> * I don't think `ReviewBoard` should be an entity at all, it is a feature that is using the `review` entity.
> * Same goes for `Message Boards`

The ERD diagram fixed and changed

**Review by Yuval-Vino — APPROVED** [review]
LGTM , time to implement!

**Review by tamirmatok — APPROVED** [review]
Great Job ! @ErezCohenn

**Comment by ormergi** [comment]
@ErezCohenn If I understand correctly User is the builtin django entity, right? if so please add correspond note.

**Comment by ErezCohenn** [comment]
> @ErezCohenn If I understand correctly User is the builtin django entity, right? if so please add correspond note.

You're right, just added.

**Review by Omeramsc — COMMENTED** [review]
- Why do we have `Review_ID` twice under Review?
- Same goes for `Message_ID`
- How do you plan `message` to work? is it a single private message, or a chat? I find the `Author` field redundant, and confusing (it is not connected to any table, how will it identify?)

Other than that - very good work!!

**Comment by ErezCohenn** [comment]
> * Why do we have `Review_ID` twice under Review?
> * Same goes for `Message_ID`
> * How do you plan `message` to work? is it a single private message, or a chat? I find the `Author` field redundant, and confusing (it is not connected to any table, how will it identify?)
> 
> Other than that - very good work!!

Notice that the `Review_ID int (FK, self)` means that its reference to another entity of review, so the review can chain,
The same is working for messages.

**Comment by Omeramsc** [comment]
> > * Why do we have `Review_ID` twice under Review?
> > * Same goes for `Message_ID`
> > * How do you plan `message` to work? is it a single private message, or a chat? I find the `Author` field redundant, and confusing (it is not connected to any table, how will it identify?)
> > 
> > Other than that - very good work!!
> 
> Notice that the `Review_ID int (FK, self)` means that its reference to another entity of review, so the review can chain, The same is working for messages.

Why would you want to chain them? 
if you want to order them one after the other on the same page, you can use the datetime to do it. 
if you want a reply to a review, it can be normal varchar (we already know who is replying)

**Comment by ErezCohenn** [comment]
> > > * Why do we have `Review_ID` twice under Review?
> > > * Same goes for `Message_ID`
> > > * How do you plan `message` to work? is it a single private message, or a chat? I find the `Author` field redundant, and confusing (it is not connected to any table, how will it identify?)
> > > 
> > > Other than that - very good work!!
> > 
> > 
> > Notice that the `Review_ID int (FK, self)` means that its reference to another entity of review, so the review can chain, The same is working for messages.
> 
> Why would you want to chain them? if you want to order them one after the other on the same page, you can use the datetime to do it. if you want a reply to a review, it can be normal varchar (we already know who is replying)
> 
> Anyway, you can't have two of the same key on a table.

But in a situation where we want a reply upon reply, how can this be realized in the method you have proposed? (by adding normal varchar field), I think we must chain the messages as we learned in the class.

**Comment by Omeramsc** [comment]
> 

In most popular review systems (Facebook, Google, AliExpress, etc), a review usually consist of 1 review and 1 reply, not a conversation. I don't see a reason for you to complicate things for yourself.

**Comment by Omeramsc** [comment]
> > > > * Why do we have `Review_ID` twice under Review?
> > > > * Same goes for `Message_ID`
> > > > * How do you plan `message` to work? is it a single private message, or a chat? I find the `Author` field redundant, and confusing (it is not connected to any table, how will it identify?)
> > > > 
> > > > Other than that - very good work!!
> > > 
> > > 
> > > Notice that the `Review_ID int (FK, self)` means that its reference to another entity of review, so the review can chain, The same is working for messages.
> > 
> > 
> > Why would you want to chain them? if you want to order them one after the other on the same page, you can use the datetime to do it. if you want a reply to a review, it can be normal varchar (we already know who is replying)
> > Anyway, you can't have two of the same key on a table.
> 
> But in a situation where we want a reply upon reply, how can this be realized in the method you have proposed? (by adding normal varchar field), I think we must chain the messages as we learned in the class.

In most popular review systems (Facebook, Google, AliExpress, etc), a review usually consist of 1 review and 1 reply, not a conversation. I don't see a reason for you to complicate things for yourself.

**Comment by ErezCohenn** [comment]
> > > > > * Why do we have `Review_ID` twice under Review?
> > > > > * Same goes for `Message_ID`
> > > > > * How do you plan `message` to work? is it a single private message, or a chat? I find the `Author` field redundant, and confusing (it is not connected to any table, how will it identify?)
> > > > > 
> > > > > Other than that - very good work!!
> > > > 
> > > > 
> > > > Notice that the `Review_ID int (FK, self)` means that its reference to another entity of review, so the review can chain, The same is working for messages.
> > > 
> > > 
> > > Why would you want to chain them? if you want to order them one after the other on the same page, you can use the datetime to do it. if you want a reply to a review, it can be normal varchar (we already know who is replying)
> > > Anyway, you can't have two of the same key on a table.
> > 
> > 
> > But in a situation where we want a reply upon reply, how can this be realized in the method you have proposed? (by adding normal varchar field), I think we must chain the messages as we learned in the class.
> 
> In most popular review systems (Facebook, Google, AliExpress, etc), a review usually consist of 1 review and 1 reply, not a conversation. I don't see a reason for you to complicate things for yourself.

Got your point, I will update the reviews table.
What about the messages? they should be a chat and not s single private message, so I think we have to stay with the
 `Message_ID int (FK, self)` field, what u think?

**Comment by tamirmatok** [comment]
I have notice that Django "User" entity includes non-mendatory fields of "First name" and "Last name",
should we still keep those fields in "Dog owner" fields ? @Omeramsc

**Comment by Omeramsc** [comment]
@ErezCohenn You can try using it with messages if that works for you (change the name of the key though).

@tamirmatok You tell me - does every entity that extends `User` need a first and last name properties?

**Comment by ErezCohenn** [comment]
> @ErezCohenn You can try using it with messages if that works for you (change the name of the key though).

Done

**Comment by tamirmatok** [comment]
> @ErezCohenn You can try using it with messages if that works for you (change the name of the key though).
> 
> @tamirmatok You tell me - does every entity that extends `User` need a first and last name properties?

I think that we can give up on them @ErezCohenn  @Omeramsc

**Review by Omeramsc — APPROVED** [review]
LGTM

**Review by ormergi — APPROVED** [review]
Thanks

**Pull request merged**
