### PR TITLE
Create static reviews for all DayCares

### LINKED ISSUE #83: Add static reviews
## Expected Behavior

Because the project uses only static users without the ability to register at the moment, there is a need for a large number of static reviews for daycares for regular work.

## Current Behavior

There are only 3 static reviews in the data migrations

## Acceptance Criteria

New migration was added to create static reviews for all DayCares

### PR DESCRIPTION
**Pull request by jeniaSakirko**
Signed-off-by: Jenia Sakirko <Jenia.Sakirko@cyberark.com>

### Desired Outcome

Reviews are created automatically for all DayCares

### Implemented Changes

New migration that create all reviews for all daycares

### Connected Issue/Story

Resolves #83 

### Definition of Done

New migration was added to create static reviews for all DayCares

#### Changelog

- [ ] The CHANGELOG has been updated
- [x] This PR does not include user-facing changes and doesn't require a
  CHANGELOG update

#### Test coverage

- [ ] This PR includes new unit and integration tests to go with the code
  changes
- [x] The changes in this PR do not require tests

#### Documentation

- [ ] Docs (e.g. `README`s) were updated in this PR
- [ ] A follow-up issue to update official docs has been filed here: [insert issue ID]()
- [x] This PR does not require updating any documentation

### CODE REVIEW

**Review by ErezCohenn — COMMENTED** [review]
I recommend to you take a look at how I implemented the static daycare users,
without using random, and using `list comprehension`.
You can take a look [here](https://github.com/redhat-beyond/Hotails/pull/690) the comments that omer left about it.

**Comment by jeniaSakirko** [comment]
> I recommend to you take a look at how I implemented the static daycare users, without using random, and using `list comprehension`. You can take a look [here](https://github.com/redhat-beyond/Hotails/pull/690) the comments that omer left about it.

IMO list comprehension when running nested loop is not so readable but its looks cleaner so I changed it, kept the random so we will have different reviews in each daycare

**Review by OfirMatasas — APPROVED** [review]
I agree with Jenia about list comprehension readability. One-lining isn't always the best option.
Besides that, great job!

**Comment by Yuval-Vino** [comment]
> > I recommend to you take a look at how I implemented the static daycare users, without using random, and using `list comprehension`. You can take a look [here](https://github.com/redhat-beyond/Hotails/pull/690) the comments that omer left about it.
> 
> IMO list comprehension when running nested loop is not so readable but its looks cleaner so I changed it, kept the random so we will have different reviews in each daycare

I have to agree that list comprehension with double for is a bit unreadable, I prefer the previous version with the append method,  anyway LGTM!

**Review by Yuval-Vino — APPROVED** [review]

**Comment by Omeramsc** [comment]
Are those static reviews used (or will be used later) for tests? if so, using random is out of the question, as those need to be reliable and explicit.
(otherwise its fine)

**Comment by jeniaSakirko** [comment]
> Are those static reviews used (or will be used later) for tests? if so, using random is out of the question, as those need to be reliable and explicit. (otherwise its fine)
> 
> P.S: I see all the reviews got a space at the beginning. might want to just add the space in the loop instead.

Its not for the tests (we already have reviews for the tests https://github.com/redhat-beyond/Hotails/blob/main/review/migrations/0002_test_data.py) the purpose of this data is to see better in the UI when using static users

**Review by ErezCohenn — APPROVED** [review]
LGTM

**Comment by Omeramsc** [comment]
> > Are those static reviews used (or will be used later) for tests? if so, using random is out of the question, as those need to be reliable and explicit. (otherwise its fine)
> > P.S: I see all the reviews got a space at the beginning. might want to just add the space in the loop instead.
> 
> Its not for the tests (we already have reviews for the tests https://github.com/redhat-beyond/Hotails/blob/main/review/migrations/0002_test_data.py) the purpose of this data is to see reviews in the UI when checking DayCare page
> 
> Regarding the space please notice that there are four reviews and the spaces are due to new line, e.g. no space in begging of the review

You're right, 
as it is a bit confusing - try using `dedent` from the `textwrap` library

**Review by Omeramsc — APPROVED** [review]
LGTM

**Pull request merged**
